/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/untitled.gltf -k 
material=\{[^}]+\}
*/

import { useGLTF, useTexture, useVideoTexture } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { animate, useMotionValue } from "framer-motion";
import { useEffect } from "react";

import * as THREE from "three";
export default function Studio(props) {
  const { section } = props;
  const { nodes, materials } = useGLTF("models/FinalScenceV2.gltf");

  const textureVscode = useVideoTexture("texture/vscode.mp4");
  const textureTwo = useVideoTexture("texture/2.mp4");
  const textureThree = useVideoTexture("texture/3.mp4");

  const texture = useTexture("texture/scenevtwo.jpg");
  texture.flipY = false;
  texture.colorSpace = THREE.SRGBColorSpace;
  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: 1,
  });
  const textureOpacity = useMotionValue(0);

  useEffect(() => {
    animate(textureOpacity, section === 0 ? 1 : 0);
  }, [section, textureOpacity]);

  useFrame(() => {
    textureMaterial.opacity = textureOpacity.get();
  });

  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="1Plane">
          <mesh
            name="Plane001"
            geometry={nodes.Plane001.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane001_1"
            geometry={nodes.Plane001_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane001_2"
            geometry={nodes.Plane001_2.geometry}
            material={textureMaterial}
          />
        </group>
        <group name="2table" position={[0, 3.958, 0]}>
          <mesh
            name="Plane002"
            geometry={nodes.Plane002.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane002_1"
            geometry={nodes.Plane002_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane002_2"
            geometry={nodes.Plane002_2.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane002_3"
            geometry={nodes.Plane002_3.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Plane002_4"
            geometry={nodes.Plane002_4.geometry}
            material={textureMaterial}
          />
        </group>
        <mesh
          name="3Keyboard1"
          geometry={nodes["3Keyboard1"].geometry}
          material={textureMaterial}
          position={[0.682, 4.466, -5.618]}
        />
        <mesh
          name="4ComputerMouse_mesh"
          geometry={nodes["4ComputerMouse_mesh"].geometry}
          material={textureMaterial}
          position={[2.396, 4.442, -5.645]}
          rotation={[Math.PI, -0.146, Math.PI]}
        />
        <mesh
          name="8Computer"
          geometry={nodes["8Computer"].geometry}
          material={textureMaterial}
          position={[4.885, 1.036, -6.121]}
        />
        <mesh
          name="9ExecutiveChair1"
          geometry={nodes["9ExecutiveChair1"].geometry}
          material={textureMaterial}
          position={[1.354, 2.54, -2.429]}
          rotation={[-Math.PI / 2, 0, 3.14]}
        />
        <group name="10Pot_Plant" position={[7.338, 4.936, -6.136]}>
          <mesh
            name="Pot_Plant"
            geometry={nodes.Pot_Plant.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Pot_Plant_1"
            geometry={nodes.Pot_Plant_1.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Pot_Plant_2"
            geometry={nodes.Pot_Plant_2.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Pot_Plant_3"
            geometry={nodes.Pot_Plant_3.geometry}
            material={textureMaterial}
          />
          <mesh
            name="Pot_Plant_4"
            geometry={nodes.Pot_Plant_4.geometry}
            material={textureMaterial}
          />
        </group>
        <mesh
          name="11Air_Conditioner1"
          geometry={nodes["11Air_Conditioner1"].geometry}
          material={textureMaterial}
          position={[1.088, 11.193, -7.22]}
        />
        <mesh
          name="13rug"
          geometry={nodes["13rug"].geometry}
          material={textureMaterial}
          position={[1.006, 0.992, 4.961]}
        />
        <group
          name="14badtz_Cylinder000"
          position={[-5.825, 0.612, 5.955]}
          rotation={[-Math.PI, 1.171, -Math.PI]}
        >
          <mesh
            name="badtz_Cylinder000-Mesh"
            geometry={nodes["badtz_Cylinder000-Mesh"].geometry}
            material={textureMaterial}
          />
          <mesh
            name="badtz_Cylinder000-Mesh_1"
            geometry={nodes["badtz_Cylinder000-Mesh_1"].geometry}
            material={textureMaterial}
          />
          <mesh
            name="badtz_Cylinder000-Mesh_2"
            geometry={nodes["badtz_Cylinder000-Mesh_2"].geometry}
            material={textureMaterial}
          />
          <mesh
            name="badtz_Cylinder000-Mesh_3"
            geometry={nodes["badtz_Cylinder000-Mesh_3"].geometry}
            material={textureMaterial}
          />
          <mesh
            name="badtz_Cylinder000-Mesh_4"
            geometry={nodes["badtz_Cylinder000-Mesh_4"].geometry}
            material={textureMaterial}
          />
          <mesh
            name="badtz_Cylinder000-Mesh_5"
            geometry={nodes["badtz_Cylinder000-Mesh_5"].geometry}
            material={textureMaterial}
          />
          <mesh
            name="badtz_Cylinder000-Mesh_6"
            geometry={nodes["badtz_Cylinder000-Mesh_6"].geometry}
            material={textureMaterial}
          />
          <mesh
            name="badtz_Cylinder000-Mesh_7"
            geometry={nodes["badtz_Cylinder000-Mesh_7"].geometry}
            material={textureMaterial}
          />
        </group>
        <mesh
          name="Monitor"
          geometry={nodes.Monitor.geometry}
          material={textureMaterial}
          position={[0.811, 4.401, -7.088]}
        />
        <mesh
          name="Tv1"
          geometry={nodes.Tv1.geometry}
          material={textureMaterial}
          position={[4.574, 5.973, -6.955]}
          rotation={[-Math.PI / 2, 0, -0.067]}
        />
        <mesh
          name="Tv1-2"
          geometry={nodes["Tv1-2"].geometry}
          material={textureMaterial}
          position={[-2.929, 5.973, -6.955]}
          rotation={[-Math.PI / 2, 0, 0.092]}
        />
        <group
          name="BigScreen"
          position={[-7.501, 8.622, 0.422]}
          rotation={[0, 1.571, 0]}
        >
          <mesh
            name="mesh1454904968001"
            geometry={nodes.mesh1454904968001.geometry}
            material={textureMaterial}
          />
          <mesh
            name="mesh1454904968001_1"
            geometry={nodes.mesh1454904968001_1.geometry}
            material={textureMaterial}
          />
        </group>
        <mesh
          name="BigScreen001"
          geometry={nodes.BigScreen001.geometry}
          position={[-7.501, 8.622, 0.422]}
          rotation={[0, 1.571, 0]}
          scale={2.257}
        >
          <meshBasicMaterial map={textureThree} toneMapped={false} />
        </mesh>
        <mesh
          name="Tv1-2001"
          geometry={nodes["Tv1-2001"].geometry}
          position={[-2.929, 5.973, -6.955]}
          rotation={[-Math.PI / 2, 0, 0.092]}
          scale={157.229}
        >
          <meshBasicMaterial map={textureThree} toneMapped={false} />
        </mesh>
        <mesh
          name="Monitor001"
          geometry={nodes.Monitor001.geometry}
          position={[0.811, 4.401, -7.088]}
          scale={868.558}
        >
          <meshBasicMaterial map={textureVscode} toneMapped={false} />
        </mesh>
        <mesh
          name="Tv1001"
          geometry={nodes.Tv1001.geometry}
          position={[4.574, 5.973, -6.955]}
          rotation={[-Math.PI / 2, 0, -0.067]}
          scale={157.229}
        >
          <meshBasicMaterial map={textureTwo} toneMapped={false} />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("models/FinalScenceV2.gltf");
